package softwarecontable;

import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**** @author Richard */

public class CuentasT extends javax.swing.JFrame {
    
    public static String fechaActual(){
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/mm/yyyy");
        return formatoFecha.format(fecha);
    }
    
    ArrayList<Contabilidad> CuentaT = new ArrayList<>();
    ArrayList<SaldoCuentaT> SaldoCuenta = new ArrayList<>();
    ArrayList<PolizaEgresosAutorizacion> PolizaAutorizada = new ArrayList<>();
    
    //llenar la tabla
    private void llenarTablaCuenta() {
        DefaultTableModel llenar = (DefaultTableModel) tbCuenta.getModel();
        Object[] fila = new Object[2];
        //primero se limpia el grid
        for (int i = 0; i < tbCuenta.getRowCount(); i++) {
            llenar.removeRow(i);
            i = i - 1;
        }
        //aqui se hace el recorrido de Equipo para llenar la tabla
        for (Contabilidad aux : CuentaT) {
            fila[0] = aux.getCargo();
            fila[1] = aux.getAbono();
            llenar.addRow(fila);
        }
    }//Fin de llenar Tabla Cuenta
    
    private void llenarTablaPolizaEgresos() {
        DefaultTableModel llenar = (DefaultTableModel) tbPolizaEgresos.getModel();
        Object[] fila = new Object[6];
        //primero se limpia el grid
        for (int i = 0; i < tbPolizaEgresos.getRowCount(); i++) {
            llenar.removeRow(i);
            i = i - 1;
        }
        //aqui se hace el recorrido de Equipo para llenar la tabla
        for (SaldoCuentaT aux : SaldoCuenta) {
            fila[0] = aux.getCuenta();
            fila[1] = aux.getSubCuenta() + " - Bancos";
            fila[2] = aux.getNameCuenta() + "     " + aux.getDescripcion();
            fila[3] = aux.getParcial();
            fila[4] = aux.getSumaCargo();
            fila[5] = aux.getsumaAbono();
            llenar.addRow(fila);
        }
    }//Fin de llenar Tabla Poliza de Egresos
    
    private void llenarTablaPolizaAutorizada() {
        DefaultTableModel llenar = (DefaultTableModel) tbPolizaAutorizada.getModel();
        Object[] fila = new Object[5];
        //primero se limpia el grid
        for (int i = 0; i < tbPolizaAutorizada.getRowCount(); i++) {
            llenar.removeRow(i);
            i = i - 1;
        }
        //aqui se hace el recorrido de Equipo para llenar la tabla
        for (PolizaEgresosAutorizacion aux : PolizaAutorizada) {
            fila[0] = aux.getRealizado();
            fila[1] = aux.getReviso();
            fila[2] = aux.getAutorizo();
            fila[3] = aux.getAuxiliares();
            fila[4] = aux.getNoPoliza();
            llenar.addRow(fila);
        }
    }//Fin de llenar Tabla Cuent
    
    public void limpiarCajas(){
        txtCargar.setText("0.0");
        txtAbonar.setText("0.0");
    }//fin de limpiarCajas
    
    

    /** Creates new form CuentasT */
    public CuentasT() {
        initComponents();
        txtCargar.setText("0.0");
        txtAbonar.setText("0.0");
        txtFecha.setText(fechaActual());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        btnEliminarFila = new javax.swing.JButton();
        txtSumAbono = new javax.swing.JTextField();
        txtSumCargo = new javax.swing.JTextField();
        txtSaldoDeudor = new javax.swing.JTextField();
        txtSaldoAcreedor = new javax.swing.JTextField();
        txtCuenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCuenta = new javax.swing.JTable();
        txtAbonar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        txtCargar = new javax.swing.JTextField();
        txtNomCuenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNoCuenta = new javax.swing.JTextField();
        txtSubCuenta = new javax.swing.JTextField();
        txtParcial = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtRealizado = new javax.swing.JTextField();
        txtRevisado = new javax.swing.JTextField();
        txtAutorizado = new javax.swing.JTextField();
        txtNoPoliza = new javax.swing.JTextField();
        txtAuxiliares = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtNomCuent = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnSalir1 = new javax.swing.JButton();
        btnGenerarPDF = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPolizaAutorizada = new javax.swing.JTable();
        txtConcepto = new javax.swing.JTextField();
        txtSumParcial = new javax.swing.JTextField();
        txtSumDebe = new javax.swing.JTextField();
        txtSumHaber = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPolizaEgresos = new javax.swing.JTable();
        txtFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRealizarSum = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hoja Electronica para Cuentas\"T\"");
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));

        btnSalir.setBackground(new java.awt.Color(36, 47, 65));
        btnSalir.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(36, 47, 65));
        btnNuevo.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnResultado.setBackground(new java.awt.Color(36, 47, 65));
        btnResultado.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        btnResultado.setForeground(new java.awt.Color(255, 255, 255));
        btnResultado.setText("Resultado");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });

        btnEliminarFila.setBackground(new java.awt.Color(36, 47, 65));
        btnEliminarFila.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        btnEliminarFila.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFila.setText("Eliminar fila");
        btnEliminarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFilaActionPerformed(evt);
            }
        });

        txtSumAbono.setBackground(new java.awt.Color(36, 47, 65));
        txtSumAbono.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtSumAbono.setForeground(new java.awt.Color(255, 255, 255));

        txtSumCargo.setBackground(new java.awt.Color(36, 47, 65));
        txtSumCargo.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtSumCargo.setForeground(new java.awt.Color(255, 255, 255));

        txtSaldoDeudor.setBackground(new java.awt.Color(36, 47, 65));
        txtSaldoDeudor.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtSaldoDeudor.setForeground(new java.awt.Color(255, 255, 255));

        txtSaldoAcreedor.setBackground(new java.awt.Color(36, 47, 65));
        txtSaldoAcreedor.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtSaldoAcreedor.setForeground(new java.awt.Color(255, 255, 255));

        txtCuenta.setBackground(new java.awt.Color(36, 47, 65));
        txtCuenta.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtCuenta.setForeground(new java.awt.Color(255, 255, 255));

        tbCuenta.setBackground(new java.awt.Color(36, 47, 65));
        tbCuenta.setForeground(new java.awt.Color(255, 255, 255));
        tbCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        jScrollPane1.setViewportView(tbCuenta);
        if (tbCuenta.getColumnModel().getColumnCount() > 0) {
            tbCuenta.getColumnModel().getColumn(0).setHeaderValue("");
            tbCuenta.getColumnModel().getColumn(1).setHeaderValue("");
        }

        txtAbonar.setBackground(new java.awt.Color(36, 47, 65));
        txtAbonar.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtAbonar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos de la Cuenta \"T\"");

        btnAgregar.setBackground(new java.awt.Color(36, 47, 65));
        btnAgregar.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtCargar.setBackground(new java.awt.Color(36, 47, 65));
        txtCargar.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtCargar.setForeground(new java.awt.Color(255, 255, 255));

        txtNomCuenta.setBackground(new java.awt.Color(36, 47, 65));
        txtNomCuenta.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtNomCuenta.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de la cuenta:");

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cargo:");

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Abono");

        jLabel8.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Poliza de Egresos");

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("No de Cuenta:");

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("No de SubCuenta:");

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Parcial:");

        txtNoCuenta.setBackground(new java.awt.Color(36, 47, 65));
        txtNoCuenta.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtNoCuenta.setForeground(new java.awt.Color(255, 255, 255));

        txtSubCuenta.setBackground(new java.awt.Color(36, 47, 65));
        txtSubCuenta.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtSubCuenta.setForeground(new java.awt.Color(255, 255, 255));

        txtParcial.setBackground(new java.awt.Color(36, 47, 65));
        txtParcial.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtParcial.setForeground(new java.awt.Color(255, 255, 255));

        btnSave.setBackground(new java.awt.Color(36, 47, 65));
        btnSave.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Realizado por:");

        jLabel13.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Revisado por:");

        jLabel14.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Autorizado por:");

        jLabel15.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Auxiliares:");

        jLabel16.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("No Poliza:");

        txtRealizado.setBackground(new java.awt.Color(36, 47, 65));
        txtRealizado.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtRealizado.setForeground(new java.awt.Color(255, 255, 255));

        txtRevisado.setBackground(new java.awt.Color(36, 47, 65));
        txtRevisado.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtRevisado.setForeground(new java.awt.Color(255, 255, 255));

        txtAutorizado.setBackground(new java.awt.Color(36, 47, 65));
        txtAutorizado.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtAutorizado.setForeground(new java.awt.Color(255, 255, 255));

        txtNoPoliza.setBackground(new java.awt.Color(36, 47, 65));
        txtNoPoliza.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtNoPoliza.setForeground(new java.awt.Color(255, 255, 255));

        txtAuxiliares.setBackground(new java.awt.Color(36, 47, 65));
        txtAuxiliares.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtAuxiliares.setForeground(new java.awt.Color(255, 255, 255));

        btnAñadir.setBackground(new java.awt.Color(36, 47, 65));
        btnAñadir.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nombre Cuenta:");

        txtNomCuent.setBackground(new java.awt.Color(36, 47, 65));
        txtNomCuent.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtNomCuent.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Descripción:");

        txtDescripcion.setBackground(new java.awt.Color(36, 47, 65));
        txtDescripcion.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(txtNomCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(513, 513, 513)
                .addComponent(jLabel8))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(txtCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(jLabel9)
                .addGap(12, 12, 12)
                .addComponent(txtNoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(txtAbonar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(331, 331, 331)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel17)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomCuent, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292)
                .addComponent(jLabel18)
                .addGap(12, 12, 12)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(713, 713, 713)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(txtParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarFila)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel13))
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel15)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRevisado, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutorizado, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAuxiliares, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSumCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldoDeudor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSumAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldoAcreedor, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(jLabel16)
                .addGap(12, 12, 12)
                .addComponent(txtNoPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(btnSalir))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtNomCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAgregar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4))
                            .addComponent(txtAbonar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel10)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtSubCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(txtNomCuent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel18))
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel11))
                    .addComponent(txtParcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnEliminarFila)
                        .addGap(15, 15, 15)
                        .addComponent(btnNuevo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel12)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel13)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel14)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txtRealizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtRevisado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtAutorizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtAuxiliares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnAñadir)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSumCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(txtSaldoDeudor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSumAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(txtSaldoAcreedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnResultado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtNoPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnSalir))))
        );

        jTabbedPane1.addTab("Cuentas T", jPanel1);

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));

        btnSalir1.setBackground(new java.awt.Color(36, 47, 65));
        btnSalir1.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir1.setText("Salir");

        btnGenerarPDF.setBackground(new java.awt.Color(36, 47, 65));
        btnGenerarPDF.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        btnGenerarPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarPDF.setText("Generar PDF");
        btnGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPDFActionPerformed(evt);
            }
        });

        btnGuardar1.setBackground(new java.awt.Color(36, 47, 65));
        btnGuardar1.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setText("Guardar");

        tbPolizaAutorizada.setBackground(new java.awt.Color(36, 47, 65));
        tbPolizaAutorizada.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        tbPolizaAutorizada.setForeground(new java.awt.Color(255, 255, 255));
        tbPolizaAutorizada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hecho por", "Revisado", "Autorizado", "Auxiliares", "Póliza No."
            }
        ));
        jScrollPane3.setViewportView(tbPolizaAutorizada);

        txtConcepto.setBackground(new java.awt.Color(36, 47, 65));
        txtConcepto.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtConcepto.setForeground(new java.awt.Color(255, 255, 255));

        txtSumParcial.setBackground(new java.awt.Color(36, 47, 65));
        txtSumParcial.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtSumParcial.setForeground(new java.awt.Color(255, 255, 255));

        txtSumDebe.setBackground(new java.awt.Color(36, 47, 65));
        txtSumDebe.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtSumDebe.setForeground(new java.awt.Color(255, 255, 255));

        txtSumHaber.setBackground(new java.awt.Color(36, 47, 65));
        txtSumHaber.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtSumHaber.setForeground(new java.awt.Color(255, 255, 255));

        tbPolizaEgresos.setBackground(new java.awt.Color(36, 47, 65));
        tbPolizaEgresos.setForeground(new java.awt.Color(255, 255, 255));
        tbPolizaEgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cuenta", "SubCuenta", "Nombre", "Parcial", "Debe", "Haber"
            }
        ));
        jScrollPane2.setViewportView(tbPolizaEgresos);
        if (tbPolizaEgresos.getColumnModel().getColumnCount() > 0) {
            tbPolizaEgresos.getColumnModel().getColumn(0).setMaxWidth(400);
            tbPolizaEgresos.getColumnModel().getColumn(1).setMaxWidth(500);
            tbPolizaEgresos.getColumnModel().getColumn(2).setMaxWidth(7000);
            tbPolizaEgresos.getColumnModel().getColumn(3).setMaxWidth(700);
            tbPolizaEgresos.getColumnModel().getColumn(4).setMaxWidth(700);
            tbPolizaEgresos.getColumnModel().getColumn(5).setMaxWidth(700);
        }

        txtFecha.setBackground(new java.awt.Color(36, 47, 65));
        txtFecha.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setText("Día/Mes/Año");

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONCEPTO:");

        jLabel7.setFont(new java.awt.Font("Felix Titling", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("POLIZA DE EGRESOS HOSTALL");

        btnRealizarSum.setBackground(new java.awt.Color(36, 47, 65));
        btnRealizarSum.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        btnRealizarSum.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarSum.setText("Realizar Sumas");
        btnRealizarSum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRealizarSumMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1012, 1012, 1012)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnRealizarSum)
                .addGap(5, 5, 5)
                .addComponent(txtSumParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtSumDebe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtSumHaber, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(874, 874, 874)
                .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnGenerarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5))
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRealizarSum)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtSumParcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtSumDebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtSumHaber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar1)
                    .addComponent(btnGenerarPDF)
                    .addComponent(btnSalir1)))
        );

        jTabbedPane1.addTab("Poliza de Egresos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        txtCuenta.setText(txtNomCuenta.getText());
        String nombre = txtNomCuenta.getText();
        double cargo = Double.parseDouble(txtCargar.getText());
        double abono = Double.parseDouble(txtAbonar.getText());
        
        Contabilidad cuenta = new Contabilidad(nombre, cargo, abono);
        CuentaT.add(cuenta);
        llenarTablaCuenta();//actualizar la tabla
        limpiarCajas();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFilaActionPerformed
        DefaultTableModel m = (DefaultTableModel)tbCuenta.getModel();
        int fila = tbCuenta.getSelectedRow();
        if (fila>=0) {
            m.removeRow(fila);
        }
    }//GEN-LAST:event_btnEliminarFilaActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        double sumatoriaCargo = 0.0;
        int totalRowc = tbCuenta.getRowCount();
        totalRowc-=1;
        for (int i = 0; i <= (totalRowc); i++) {
            double sum = Double.parseDouble(String.valueOf(tbCuenta.getValueAt(i, 0)));
            sumatoriaCargo+=sum;
            txtSumCargo.setText(""+sumatoriaCargo);
        }
        
        double sumatoriaAbono = 0.0;
        int totalRowa = tbCuenta.getRowCount();
        totalRowa-=1;
        for (int i = 0; i <= (totalRowa); i++) {
            double sum = Double.parseDouble(String.valueOf(tbCuenta.getValueAt(i, 1)));
            sumatoriaAbono+=sum;
            txtSumAbono.setText(""+sumatoriaAbono);
        }
        
        if (sumatoriaCargo > sumatoriaAbono) {
            double sumaDeudor = sumatoriaCargo - sumatoriaAbono;
            txtSaldoDeudor.setText(""+sumaDeudor);
        } else if (sumatoriaCargo < sumatoriaAbono) {
            double sumaAcreedor = sumatoriaAbono - sumatoriaCargo;
            txtSaldoAcreedor.setText(""+sumaAcreedor);
        }
    }//GEN-LAST:event_btnResultadoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        DefaultTableModel m = (DefaultTableModel)tbCuenta.getModel();
        txtNomCuenta.setText("");
        txtCargar.setText("0.0");
        txtAbonar.setText("0.0");
        txtCuenta.setText("");
        txtSumCargo.setText("0.0");
        txtSumAbono.setText("0.0");
        txtSaldoDeudor.setText("");
        txtSaldoAcreedor.setText("");
        
        for (int i = 0; i < tbCuenta.getRowCount(); i++) {
            m.removeRow(i);
            i-=1;                                                                           
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRealizarSumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarSumMousePressed
        //realizar las sumas de la poliza de egresos (parcial, debe, haber)
        double sumatoriaParcial = 0.0;
        int totalRowp = tbPolizaEgresos.getRowCount();
        totalRowp-=1;
        for (int i = 0; i <= (totalRowp); i++) {
        double sum = Double.parseDouble(String.valueOf(tbPolizaEgresos.getValueAt(i, 3)));
        sumatoriaParcial+=sum;
        txtSumParcial.setText(""+sumatoriaParcial);
        }
        
        double sumatoriaDebe = 0.0;
        int totalRowc = tbPolizaEgresos.getRowCount();
        totalRowc-=1;
        for (int i = 0; i <= (totalRowc); i++) {
        double sum = Double.parseDouble(String.valueOf(tbPolizaEgresos.getValueAt(i, 4)));
        sumatoriaDebe+=sum;
        txtSumDebe.setText(""+sumatoriaDebe);
        }
        
        double sumatoriaHaber = 0.0;
        int totalRowa = tbPolizaEgresos.getRowCount();
        totalRowa-=1;
        for (int i = 0; i <= (totalRowa); i++) {
        double sum = Double.parseDouble(String.valueOf(tbPolizaEgresos.getValueAt(i, 5)));
        sumatoriaHaber+=sum;
        txtSumHaber.setText(""+sumatoriaHaber);
        }
    }//GEN-LAST:event_btnRealizarSumMousePressed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String nombrecuenta = txtCuenta.getText();
        double sumcargar = Double.parseDouble(txtSumCargo.getText());
        double sumabono = Double.parseDouble(txtSumAbono.getText());
        int cuenta = Integer.parseInt(txtNoCuenta.getText());
        int subcuenta = Integer.parseInt(txtSubCuenta.getText());
        double parcial = Double.parseDouble(txtParcial.getText());
        String namecuenta = txtNomCuent.getText();
        String descripcion = txtDescripcion.getText();
        SaldoCuentaT saldoCuenta = new SaldoCuentaT(namecuenta, sumcargar, sumabono, cuenta,
                subcuenta, parcial, namecuenta, descripcion);
        SaldoCuenta.add(saldoCuenta);
        llenarTablaPolizaEgresos();
        JOptionPane.showMessageDialog(this, "Registro guardado correctamete");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String realizado = txtRealizado.getText();
        String reviso = txtRevisado.getText();
        String autorizo = txtAutorizado.getText();
        String auxiliares = txtAuxiliares.getText();
        int nopoliza = Integer.parseInt(txtNoPoliza.getText());
        PolizaEgresosAutorizacion polizaacept = new PolizaEgresosAutorizacion(realizado,
                reviso, autorizo, auxiliares, nopoliza);
        PolizaAutorizada.add(polizaacept);
        llenarTablaPolizaAutorizada();
        JOptionPane.showMessageDialog(this, "Registro guardado correctamete");
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPDFActionPerformed
        MessageFormat header= new MessageFormat("Poliza de Egresos");
        MessageFormat footer= new MessageFormat("");
        try{
        
        tbPolizaEgresos.print(JTable.PrintMode.NORMAL, header, footer);
        
        }catch (java.awt.print.PrinterException e){
        System.err.format("No se puede imprimir %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnGenerarPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuentasT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuentasT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuentasT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuentasT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuentasT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnEliminarFila;
    private javax.swing.JButton btnGenerarPDF;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRealizarSum;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbCuenta;
    private javax.swing.JTable tbPolizaAutorizada;
    public static javax.swing.JTable tbPolizaEgresos;
    private javax.swing.JTextField txtAbonar;
    private javax.swing.JTextField txtAutorizado;
    private javax.swing.JTextField txtAuxiliares;
    private javax.swing.JTextField txtCargar;
    private javax.swing.JTextField txtConcepto;
    public static javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNoCuenta;
    private javax.swing.JTextField txtNoPoliza;
    private javax.swing.JTextField txtNomCuent;
    private javax.swing.JTextField txtNomCuenta;
    private javax.swing.JTextField txtParcial;
    private javax.swing.JTextField txtRealizado;
    private javax.swing.JTextField txtRevisado;
    private javax.swing.JTextField txtSaldoAcreedor;
    private javax.swing.JTextField txtSaldoDeudor;
    private javax.swing.JTextField txtSubCuenta;
    public static javax.swing.JTextField txtSumAbono;
    public static javax.swing.JTextField txtSumCargo;
    private javax.swing.JTextField txtSumDebe;
    private javax.swing.JTextField txtSumHaber;
    private javax.swing.JTextField txtSumParcial;
    // End of variables declaration//GEN-END:variables


}
